name: Conditional Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select deployment environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production
        default: 'development'

jobs:
  conditional-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Production deployment step
        if: ${{ github.event.inputs.environment == 'production' }}
        run: echo "Deploying to production!"

      - name: Test environment step
        if: ${{ github.event.inputs.environment == 'development' || github.event.inputs.environment == 'staging' }}
        run: echo "Running in test mode"

      - name: Always show selected environment
        run: echo "Selected environment: ${{ github.event.inputs.environment }}"
